# Generated by Django 2.2.7 on 2020-02-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=35, unique=True)),
                ('email', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=20)),
            ],
        ),
    ]
